### ISSUE TITLE
spm_encode: No such file or directory

### ISSUE THREAD

**Issue by zzzul9** [facebookresearch/LASER#222]
I try to calculate sentence embedding of text file using LASER, but it shows below error messages.

![issue_captured](https://user-images.githubusercontent.com/124219996/216206590-797bfd61-55da-45df-9cdd-2e84fbc23b11.jpg)

Of course installation of external tools & dependencies were all complete.
Please let me know how to fix this case.
Thanks!

**Comment by heffernankevin** [comment]
Hi @zzzul9! Can you double-check that the `spm_encode` binary is installed in the directory: `LASER/tools-external/sentencepiece-master/build/src` ? Sometimes there can be issues during compilation of the binaries.

**Comment by zzzul9** [comment]
Hi,
Thank you for your kindness.
When I did "download third party software by bash ./install_external_tools.sh" then 'sentencepiece' installed below location.

/LASER/tools-external/sentencepiece-master/src

I had no found not only your mentioned locations but also any binaries.
Do I have to build the binaries for spm_encode?

**Comment by heffernankevin** [comment]
Can you try re-running the script: `./install_external_tools.sh` and share if you see any error messages?

**Comment by ShakeHakobyan** [comment]
I had the same issue. I did a build in the build folder and the necessary files appeared.
cmake ..

**Comment by zzzul9** [comment]
Sorry for late reply.
I had retry installation procedure after removing as your guide, but couldn't find any error message.
Please check attached log file and let me know what I missed something.
Thank you very much!
[log-install_external_tools.txt](https://github.com/facebookresearch/LASER/files/10809825/log-install_external_tools.txt)

**Comment by heffernankevin** [comment]
Thanks for the error log @zzzul9! I also don't see any errors. Can you perhaps try what @ShakeHakobyan suggested? cd first into the "build" directory which the script created e.g., 

`cd /home/user/workspace/MMT/LASER/tools-external/sentencepiece-master/build`

Then try building the binaries:

```
cmake ..
make -j 10
```

**Comment by zzzul9** [comment]
[heffernankevin](https://github.com/heffernankevin)
[ShakeHakobyan](https://github.com/ShakeHakobyan)
Really thanks!
The problem was solved with your kindly guidance.

**Comment by thyripian** [comment]
I have this same problem.  I navigated to the build dir and ran cmake .. (which worked) and make -j 10 (which did not). 

The latter resulted in:
$ make -j 10
make: *** No targets specified and no makefile found.  Stop.

When I tried running embed.sh again, I still get an error stating:

2023-06-05 01:23:32,760 | ERROR | preprocess | /usr/bin/bash: line 1: C:/Users/[USER]/LASER/tools-external/sentencepiece-master/build/src/spm_encode: No such file or directory

**Comment by heffernankevin** [comment]
Hi @thyripian, can you share the outputs of: `cmake ..` From your error it seems that the makefile was not created.
